import { NextResponse } from 'next/server';

// All properties in a single array
const properties = [
  {
    id: 1,
    image: '/assets/bungalow.jpg',
    label: 'Modern Living House',
    price: '$12,750,000',
    address: '20724 Visa Court, London, CA 95476',
    area: '1200 sq.ft',
    bedroom: '4',
    bathroom: '3',
    description: 'This is a beautiful living house with a modern design and a spacious living room. Perfect for families looking for comfort and style.',
    status: 'For Sale',
    type: 'House',
    category: 'Living',
    year: '2025',
    agent: 'John Doe',
    agent_image: '/assets/john_doe.jpg',
    agent_phone: '+1 (234) 567-890',
    agent_email: 'john.doe@example.com',
    agent_website: 'https://www.john-doe.com',
    agent_facebook: 'https://www.facebook.com/john.doe',
    agent_twitter: 'https://www.twitter.com/john.doe',
    agent_instagram: 'https://www.instagram.com/john.doe',
    agent_linkedin: 'https://www.linkedin.com/in/john.doe',
  },
  {
    id: 2,
    image: '/assets/house_villa.jpg',
    label: 'Luxury Villa with Pool',
    price: '$18,500,000',
    address: '123 Ocean View, Malibu, CA 90265',
    area: '3000 sq.ft',
    bedroom: '6',
    bathroom: '5',
    description: 'An exquisite villa offering panoramic ocean views and a private infinity pool. Ideal for those seeking an opulent lifestyle.',
    status: 'For Sale',
    type: 'Villa',
    category: 'Villa',
    year: '2023',
    agent: 'Emily Johnson',
    agent_image: '/assets/emily_johnson.jpg',
    agent_phone: '+1 (987) 654-321',
    agent_email: 'emily.johnson@example.com',
    agent_website: 'https://www.emily-johnson.com',
    agent_facebook: 'https://www.facebook.com/emily.johnson',
    agent_twitter: 'https://www.twitter.com/emily.johnson',
    agent_instagram: 'https://www.instagram.com/emily.johnson',
    agent_linkedin: 'https://www.linkedin.com/in/emily.johnson',
  },
  {
    id: 3,
    image: '/assets/house_apartment.jpg',
    label: 'Downtown Apartment',
    price: '$750,000',
    address: '456 City Center, New York, NY 10001',
    area: '800 sq.ft',
    bedroom: '2',
    bathroom: '2',
    description: 'Modern apartment in the heart of the city, perfect for urban living. Close to all amenities and public transport.',
    status: 'For Rent',
    type: 'Apartment',
    category: 'Apartment',
    year: '2020',
    agent: 'Michael Brown',
    agent_image: '/assets/micheal_brown.jpg',
    agent_phone: '+1 (555) 123-4567',
    agent_email: 'michael.brown@example.com',
    agent_website: 'https://www.michael-brown.com',
    agent_facebook: 'https://www.facebook.com/michael.brown',
    agent_twitter: 'https://www.twitter.com/michael.brown',
    agent_instagram: 'https://www.instagram.com/michael.brown',
  },
  {
    id: 4,
    image: '/assets/office_floor.jpg',
    label: 'Spacious Office Floor',
    price: '$5,000,000',
    address: '789 Business Park, San Francisco, CA 94105',
    area: '5000 sq.ft',
    width: '1000 sq.ft',
    height: '1000 sq.ft',
    description: 'A large, modern office space suitable for growing businesses. Features open-plan areas and private offices.',
    status: 'For Sale',
    type: 'Office',
    category: 'Office',
    year: '2018',
    agent: 'Frank Thomas',
    agent_image: '/assets/frank-thomas.jpg',
    agent_phone: '+1 (111) 222-3333',
    agent_email: 'frank.thomas@example.com',
    agent_website: 'https://www.frank-thomas.com',
    agent_facebook: 'https://www.facebook.com/frank.thomas',
    agent_twitter: 'https://www.twitter.com/frank.thomas',
    agent_instagram: 'https://www.instagram.com/frank.thomas',
    agent_linkedin: 'https://www.linkedin.com/in/frank.thomas',
  },
  {
    id: 5,
    image: '/assets/red-glass.jpg',
    label: 'Red Glass Villa',
    price: '$2,500,000',
    address: '101 Rural Road, Austin, TX 78701',
    area: '1700 sq.ft',
    description: 'An expansive plot of land ideal for commercial or residential development. Located in a rapidly growing area.',
    status: 'For Sale',
    type: 'Land',
    category: 'living',
    year: 'N/A',
    agent: 'Steven Green',
    agent_image: '/assets/steven-green.jpg',
    agent_phone: '+1 (444) 555-6666',
    agent_email: 'steven.green@example.com',
    agent_website: 'https://www.steven-green.com',
    agent_facebook: 'https://www.facebook.com/steven.green',
    agent_twitter: 'https://www.twitter.com/steven.green',
    agent_instagram: 'https://www.instagram.com/steven.green',
  },
  {
    id: 6,
    image: '/assets/butter-storey.jpg',
    label: 'Butterfly Storey House',
    price: '$2,500,000',
    address: '101 Rural Road, Austin, TX 78701',
    area: '1700 sq.ft',
    description: 'An expansive plot of land ideal for commercial or residential development. Located in a rapidly growing area.',
    status: 'For Sale',
    type: 'Land',
    category: 'Land',
    year: 'N/A',
    agent: 'Steven Green',
    agent_image: '/assets/steven-green.jpg',
    agent_phone: '+1 (444) 555-6666',
    agent_email: 'steven.green@example.com',
    agent_website: 'https://www.steven-green.com',
    agent_facebook: 'https://www.facebook.com/steven.green',
    agent_twitter: 'https://www.twitter.com/steven.green',
    agent_instagram: 'https://www.instagram.com/steven.green',
  },
  {
    id: 7,
    image: '/assets/salem-property.jpg',
    label: 'Salem Property Estate',
    price: '$12,500,000',
    address: '101 Rural Road, Austin, TX 78701',
    area: '1700 sq.ft',
    description: 'An expansive plot of land ideal for commercial or residential development. Located in a rapidly growing area.',
    status: 'For Sale',
    type: 'Land',
    category: 'Land',
    year: 'N/A',
    agent: 'Steven Green',
    agent_image: '/assets/steven-green.jpg',
    agent_phone: '+1 (444) 555-6666',
    agent_email: 'steven.green@example.com',
    agent_website: 'https://www.steven-green.com',
    agent_facebook: 'https://www.facebook.com/steven.green',
    agent_twitter: 'https://www.twitter.com/steven.green',
    agent_instagram: 'https://www.instagram.com/steven.green',
  },
  {
    id: 8,
    image: '/assets/estate-property.jpg',
    label: 'Prime Land for Development',
    price: '$2,500,000',
    address: '101 Rural Road, Austin, TX 78701',
    area: '1700 sq.ft',
    description: 'An expansive plot of land ideal for commercial or residential development. Located in a rapidly growing area.',
    status: 'For Sale',
    type: 'Land',
    category: 'Land',
    year: 'N/A',
    agent: 'Steven Green',
    agent_image: '/assets/steven-green.jpg',
    agent_phone: '+1 (444) 555-6666',
    agent_email: 'steven.green@example.com',
    agent_website: 'https://www.steven-green.com',
    agent_facebook: 'https://www.facebook.com/steven.green',
    agent_twitter: 'https://www.twitter.com/steven.green',
    agent_instagram: 'https://www.instagram.com/steven.green',
  },
  {
    id: 9,
    image: '/assets/estate-property.jpg',
    label: 'Prime Land for Development',
    price: '$2,500,000',
    address: '101 Rural Road, Austin, TX 78701',
    area: '1700 sq.ft',
    description: 'An expansive plot of land ideal for commercial or residential development. Located in a rapidly growing area.',
    status: 'For Sale',
    type: 'Land',
    category: 'Land',
    year: 'N/A',
    agent: 'Steven Green',
    agent_image: '/assets/steven-green.jpg',
    agent_phone: '+1 (444) 555-6666',
    agent_email: 'steven.green@example.com',
    agent_website: 'https://www.steven-green.com',
    agent_facebook: 'https://www.facebook.com/steven.green',
    agent_twitter: 'https://www.twitter.com/steven.green',
    agent_instagram: 'https://www.instagram.com/steven.green',
  },
  {
    id: 10,
    image: '/assets/estate-property.jpg',
    label: 'Prime Land for Development',
    price: '$2,500,000',
    address: '101 Rural Road, Austin, TX 78701',
    area: '1700 sq.ft',
    description: 'An expansive plot of land ideal for commercial or residential development. Located in a rapidly growing area.',
    status: 'For Sale',
    type: 'Land',
    category: 'Land',
    year: 'N/A',
    agent: 'Steven Green',
    agent_image: '/assets/steven-green.jpg',
    agent_phone: '+1 (444) 555-6666',
    agent_email: 'steven.green@example.com',
    agent_website: 'https://www.steven-green.com',
    agent_facebook: 'https://www.facebook.com/steven.green',
    agent_twitter: 'https://www.twitter.com/steven.green',
    agent_instagram: 'https://www.instagram.com/steven.green',
  },
  {
    id: 11,
    image: '/assets/estate-property.jpg',
    label: 'Prime Land for Development',
    price: '$2,500,000',
    address: '101 Rural Road, Austin, TX 78701',
    area: '1700 sq.ft',
    description: 'An expansive plot of land ideal for commercial or residential development. Located in a rapidly growing area.',
    status: 'For Sale',
    type: 'Land',
    category: 'Land',
    year: 'N/A',
    agent: 'Steven Green',
    agent_image: '/assets/steven-green.jpg',
    agent_phone: '+1 (444) 555-6666',
    agent_email: 'steven.green@example.com',
    agent_website: 'https://www.steven-green.com',
    agent_facebook: 'https://www.facebook.com/steven.green',
    agent_twitter: 'https://www.twitter.com/steven.green',
    agent_instagram: 'https://www.instagram.com/steven.green',
  },
  {
    id: 12,
    image: '/assets/estate-property.jpg',
    label: 'Prime Land for Development',
    price: '$2,500,000',
    address: '101 Rural Road, Austin, TX 78701',
    area: '1700 sq.ft',
    description: 'An expansive plot of land ideal for commercial or residential development. Located in a rapidly growing area.',
    status: 'For Sale',
    type: 'Land',
    category: 'Land',
    year: 'N/A',
    agent: 'Steven Green',
    agent_image: '/assets/steven-green.jpg',
    agent_phone: '+1 (444) 555-6666',
    agent_email: 'steven.green@example.com',
    agent_website: 'https://www.steven-green.com',
    agent_facebook: 'https://www.facebook.com/steven.green',
    agent_twitter: 'https://www.twitter.com/steven.green',
    agent_instagram: 'https://www.instagram.com/steven.green',
  },
  {
    id: 13,
    image: '/assets/bungalow.jpg',
    label: 'Cozy Family Bungalow',
    price: '$850,000',
    address: '123 Forest Lane, Springfield, IL 62704',
    area: '1500 sq.ft',
    bedroom: '3',
    bathroom: '2',
    description: 'A charming bungalow, recently renovated with a large backyard. Ideal for a small family looking for comfort.',
    status: 'For Sale',
    type: 'House',
    category: 'Living',
    year: '2010',
    agent: 'Emily Johnson',
    agent_image: '/assets/emily_johnson.jpg',
    agent_phone: '+1 (987) 654-321',
    agent_email: 'emily.johnson@example.com',
    agent_website: 'https://www.emily-johnson.com',
    agent_facebook: 'https://www.facebook.com/emily.johnson',
    agent_twitter: 'https://www.twitter.com/emily.johnson',
    agent_instagram: 'https://www.instagram.com/emily.johnson',
    agent_linkedin: 'https://www.linkedin.com/in/emily.johnson',
  },
  {
    id: 14,
    image: '/assets/house-north.jpg',
    label: 'Northside Modern Home',
    price: '$1,500,000',
    address: '789 Oak Avenue, Northville, MI 48167',
    area: '2200 sq.ft',
    bedroom: '4',
    bathroom: '3',
    description: 'Stylish modern home with open concept living, gourmet kitchen, and spacious master suite. Prime location.',
    status: 'For Sale',
    type: 'House',
    category: 'Living',
    year: '2022',
    agent: 'John Doe',
    agent_image: '/assets/john_doe.jpg',
    agent_phone: '+1 (234) 567-890',
    agent_email: 'john.doe@example.com',
    agent_website: 'https://www.john-doe.com',
    agent_facebook: 'https://www.facebook.com/john.doe',
    agent_twitter: 'https://www.twitter.com/john.doe',
    agent_instagram: 'https://www.instagram.com/john.doe',
    agent_linkedin: 'https://www.linkedin.com/in/john.doe',
  },
  {
    id: 15,
    image: '/assets/fairview.jpg',
    label: 'Fairview Family Residence',
    price: '$980,000',
    address: '456 Willow Creek, Fairview, GA 30213',
    area: '1800 sq.ft',
    bedroom: '3',
    bathroom: '2',
    description: 'Well-maintained family home in a quiet neighborhood with excellent schools. Large garden and patio area.',
    status: 'For Sale',
    type: 'House',
    category: 'Living',
    year: '2005',
    agent: 'Michael Brown',
    agent_image: '/assets/micheal_brown.jpg',
    agent_phone: '+1 (555) 123-4567',
    agent_email: 'michael.brown@example.com',
    agent_website: 'https://www.michael-brown.com',
    agent_facebook: 'https://www.facebook.com/michael.brown',
    agent_twitter: 'https://www.twitter.com/michael.brown',
    agent_instagram: 'https://www.instagram.com/michael.brown',
  },
  {
    id: 16,
    image: '/assets/franklin.jpg',
    label: 'Franklin Parkside Home',
    price: '$1,100,000',
    address: '789 Parkside Drive, Franklin, TN 37064',
    area: '2000 sq.ft',
    bedroom: '4',
    bathroom: '3',
    description: 'Beautiful home facing a serene park, perfect for outdoor enthusiasts. Modern interiors with classic charm.',
    status: 'For Sale',
    type: 'House',
    category: 'Living',
    year: '2015',
    agent: 'Frank Thomas',
    agent_image: '/assets/frank-thomas.jpg',
    agent_phone: '+1 (111) 222-3333',
    agent_email: 'frank.thomas@example.com',
    agent_website: 'https://www.frank-thomas.com',
    agent_facebook: 'https://www.facebook.com/frank.thomas',
    agent_twitter: 'https://www.twitter.com/frank.thomas',
    agent_instagram: 'https://www.instagram.com/frank.thomas',
    agent_linkedin: 'https://www.linkedin.com/in/frank.thomas',
  },
  {
    id: 17,
    image: '/assets/greenville.jpg',
    label: 'Greenville Executive House',
    price: '$1,950,000',
    address: '101 Executive Blvd, Greenville, SC 29601',
    area: '2800 sq.ft',
    bedroom: '5',
    bathroom: '4',
    description: 'Spacious executive home in a prime, upscale community. Features high-end finishes and a private office.',
    status: 'For Sale',
    type: 'House',
    category: 'Living',
    year: '2021',
    agent: 'Steven Green',
    agent_image: '/assets/steven-green.jpg',
    agent_phone: '+1 (444) 555-6666',
    agent_email: 'steven.green@example.com',
    agent_website: 'https://www.steven-green.com',
    agent_facebook: 'https://www.facebook.com/steven.green',
    agent_twitter: 'https://www.twitter.com/steven.green',
    agent_instagram: 'https://www.instagram.com/steven.green',
  },
  {
    id: 18,
    image: '/assets/red-glass.jpg',
    label: 'Modern Glass Villa',
    price: '$22,000,000',
    address: '777 Sunset Blvd, Los Angeles, CA 90069',
    area: '4500 sq.ft',
    bedroom: '7',
    bathroom: '6',
    description: 'A stunning modern villa with panoramic glass walls, offering breathtaking views and unparalleled luxury.',
    status: 'For Sale',
    type: 'Villa',
    category: 'Villa',
    year: '2024',
    agent: 'Emily Johnson',
    agent_image: '/assets/emily_johnson.jpg',
    agent_phone: '+1 (987) 654-321',
    agent_email: 'emily.johnson@example.com',
    agent_website: 'https://www.emily-johnson.com',
    agent_facebook: 'https://www.facebook.com/emily.johnson',
    agent_twitter: 'https://www.twitter.com/emily.johnson',
    agent_instagram: 'https://www.instagram.com/emily.johnson',
    agent_linkedin: 'https://www.linkedin.com/in/emily.johnson',
  },
  {
    id: 19,
    image: '/assets/rose.jpg',
    label: 'Rose Garden Villa',
    price: '$15,500,000',
    address: '555 Blossom Lane, Beverly Hills, CA 90210',
    area: '3800 sq.ft',
    bedroom: '6',
    bathroom: '5',
    description: 'Elegant villa surrounded by lush rose gardens, offering privacy and a serene living experience.',
    status: 'For Sale',
    type: 'Villa',
    category: 'Villa',
    year: '2020',
    agent: 'Emily Johnson',
    agent_image: '/assets/emily_johnson.jpg',
    agent_phone: '+1 (987) 654-321',
    agent_email: 'emily.johnson@example.com',
    agent_website: 'https://www.emily-johnson.com',
    agent_facebook: 'https://www.facebook.com/emily.johnson',
    agent_twitter: 'https://www.twitter.com/emily.johnson',
    agent_instagram: 'https://www.instagram.com/emily.johnson',
    agent_linkedin: 'https://www.linkedin.com/in/emily.johnson',
  },
  {
    id: 20,
    image: '/assets/los_angeles_1.jpg',
    label: 'LA Luxury Apartment',
    price: '$1,200,000',
    address: '888 Grand Ave, Los Angeles, CA 90015',
    area: '1100 sq.ft',
    bedroom: '2',
    bathroom: '2',
    description: 'High-rise apartment with city views, modern amenities, and access to exclusive building facilities.',
    status: 'For Rent',
    type: 'Apartment',
    category: 'Apartment',
    year: '2021',
    agent: 'Michael Brown',
    agent_image: '/assets/micheal_brown.jpg',
    agent_phone: '+1 (555) 123-4567',
    agent_email: 'michael.brown@example.com',
    agent_website: 'https://www.michael-brown.com',
    agent_facebook: 'https://www.facebook.com/michael.brown',
    agent_twitter: 'https://www.twitter.com/michael.brown',
    agent_instagram: 'https://www.instagram.com/michael.brown',
  },
  {
    id: 21,
    image: '/assets/los_angeles_2.jpg',
    label: 'Hollywood Hills Apartment',
    price: '$950,000',
    address: '101 Starry Ave, Hollywood, CA 90046',
    area: '900 sq.ft',
    bedroom: '1',
    bathroom: '1',
    description: 'Chic apartment in Hollywood Hills, perfect for a single professional. Close to entertainment and dining.',
    status: 'For Rent',
    type: 'Apartment',
    category: 'Apartment',
    year: '2019',
    agent: 'Michael Brown',
    agent_image: '/assets/micheal_brown.jpg',
    agent_phone: '+1 (555) 123-4567',
    agent_email: 'michael.brown@example.com',
    agent_website: 'https://www.michael-brown.com',
    agent_facebook: 'https://www.facebook.com/michael.brown',
    agent_twitter: 'https://www.twitter.com/michael.brown',
    agent_instagram: 'https://www.instagram.com/michael.brown',
  },
  {
    id: 22,
    image: '/assets/madison.jpg',
    label: 'Madison Avenue Loft',
    price: '$1,500,000',
    address: '400 Madison Ave, New York, NY 10017',
    area: '1300 sq.ft',
    bedroom: '2',
    bathroom: '2',
    description: 'Spacious loft apartment in a prime Midtown location. High ceilings and large windows offer abundant natural light.',
    status: 'For Sale',
    type: 'Apartment',
    category: 'Apartment',
    year: '2017',
    agent: 'Michael Brown',
    agent_image: '/assets/micheal_brown.jpg',
    agent_phone: '+1 (555) 123-4567',
    agent_email: 'michael.brown@example.com',
    agent_website: 'https://www.michael-brown.com',
    agent_facebook: 'https://www.facebook.com/michael.brown',
    agent_twitter: 'https://www.twitter.com/michael.brown',
    agent_instagram: 'https://www.instagram.com/michael.brown',
  },
  {
    id: 23,
    image: '/assets/washington.jpg',
    label: 'Washington DC Condo',
    price: '$700,000',
    address: '123 Capitol St, Washington, DC 20001',
    area: '750 sq.ft',
    bedroom: '1',
    bathroom: '1',
    description: 'Modern condo in the heart of DC, ideal for professionals. Walking distance to government buildings and attractions.',
    status: 'For Rent',
    type: 'Apartment',
    category: 'Apartment',
    year: '2018',
    agent: 'Michael Brown',
    agent_image: '/assets/micheal_brown.jpg',
    agent_phone: '+1 (555) 123-4567',
    agent_email: 'michael.brown@example.com',
    agent_website: 'https://www.michael-brown.com',
    agent_facebook: 'https://www.facebook.com/michael.brown',
    agent_twitter: 'https://www.twitter.com/michael.brown',
    agent_instagram: 'https://www.instagram.com/michael.brown',
  },
  {
    id: 24,
    image: '/assets/scrapper_office.jpg',
    label: 'High-Rise Office Space',
    price: '$7,500,000',
    address: '999 Corporate Tower, Chicago, IL 60606',
    area: '6000 sq.ft',
    description: 'Premium office space on a high floor with panoramic city views. Perfect for a growing tech company.',
    status: 'For Sale',
    type: 'Office',
    category: 'Office',
    year: '2023',
    agent: 'Frank Thomas',
    agent_image: '/assets/frank-thomas.jpg',
    agent_phone: '+1 (111) 222-3333',
    agent_email: 'frank.thomas@example.com',
    agent_website: 'https://www.frank-thomas.com',
    agent_facebook: 'https://www.facebook.com/frank.thomas',
    agent_twitter: 'https://www.twitter.com/frank.thomas',
    agent_instagram: 'https://www.instagram.com/frank.thomas',
    agent_linkedin: 'https://www.linkedin.com/in/frank.thomas',
  },
  {
    id: 25,
    image: '/assets/team-accolades.jpg',
    label: 'Creative Co-working Space',
    price: '$3,000,000',
    address: '123 Innovation Alley, Portland, OR 97204',
    area: '3500 sq.ft',
    description: 'Vibrant and inspiring co-working space, ideal for startups and creative teams. Fully furnished and equipped.',
    status: 'For Rent',
    type: 'Office',
    category: 'Office',
    year: '2019',
    agent: 'Frank Thomas',
    agent_image: '/assets/frank-thomas.jpg',
    agent_phone: '+1 (111) 222-3333',
    agent_email: 'frank.thomas@example.com',
    agent_website: 'https://www.frank-thomas.com',
    agent_facebook: 'https://www.facebook.com/frank.thomas',
    agent_twitter: 'https://www.twitter.com/frank.thomas',
    agent_instagram: 'https://www.instagram.com/frank.thomas',
    agent_linkedin: 'https://www.linkedin.com/in/frank.thomas',
  },
  {
    id: 26,
    image: '/assets/bristol.jpg',
    label: 'Bristol Family Villa',
    price: '$19,000,000',
    address: '456 Hilltop Drive, Bristol, UK',
    area: '4000 sq.ft',
    bedroom: '5',
    bathroom: '4',
    description: 'A spacious family villa located on a hilltop with stunning panoramic views. Modern design with classic touches.',
    status: 'For Sale',
    type: 'Villa',
    category: 'Villa',
    year: '2022',
    agent: 'Emily Johnson',
    agent_image: '/assets/emily_johnson.jpg',
    agent_phone: '+1 (987) 654-321',
    agent_email: 'emily.johnson@example.com',
    agent_website: 'https://www.emily-johnson.com',
    agent_facebook: 'https://www.facebook.com/emily.johnson',
    agent_twitter: 'https://www.twitter.com/emily.johnson',
    agent_instagram: 'https://www.instagram.com/emily.johnson',
    agent_linkedin: 'https://www.linkedin.com/in/emily.johnson',
  },
  {
    id: 27,
    image: '/assets/sea.jpg',
    label: 'Seaside Luxury Villa',
    price: '$25,000,000',
    address: '10 Oceanfront, Miami, FL 33139',
    area: '5000 sq.ft',
    bedroom: '8',
    bathroom: '7',
    description: 'An exclusive beachfront villa with direct access to the sea, private pier, and expansive outdoor living spaces.',
    status: 'For Sale',
    type: 'Villa',
    category: 'Villa',
    year: '2023',
    agent: 'Emily Johnson',
    agent_image: '/assets/emily_johnson.jpg',
    agent_phone: '+1 (987) 654-321',
    agent_email: 'emily.johnson@example.com',
    agent_website: 'https://www.emily-johnson.com',
    agent_facebook: 'https://www.facebook.com/emily.johnson',
    agent_twitter: 'https://www.twitter.com/emily.johnson',
    agent_instagram: 'https://www.instagram.com/emily.johnson',
    agent_linkedin: 'https://www.linkedin.com/in/emily.johnson',
  },
  {
    id: 28,
    image: '/assets/fairview_2.jpg',
    label: 'Fairview Modern Apartment',
    price: '$800,000',
    address: '123 Riverfront, Fairview, CO 80203',
    area: '850 sq.ft',
    bedroom: '2',
    bathroom: '1',
    description: 'Contemporary apartment with river views, ideal for individuals or couples. Close to downtown amenities.',
    status: 'For Rent',
    type: 'Apartment',
    category: 'Apartment',
    year: '2020',
    agent: 'Michael Brown',
    agent_image: '/assets/micheal_brown.jpg',
    agent_phone: '+1 (555) 123-4567',
    agent_email: 'michael.brown@example.com',
    agent_website: 'https://www.michael-brown.com',
    agent_facebook: 'https://www.facebook.com/michael.brown',
    agent_twitter: 'https://www.twitter.com/michael.brown',
    agent_instagram: 'https://www.instagram.com/michael.brown',
  },
  {
    id: 29,
    image: '/assets/salem.jpg',
    label: 'Salem City Apartment',
    price: '$650,000',
    address: '456 Central St, Salem, MA 01970',
    area: '700 sq.ft',
    bedroom: '1',
    bathroom: '1',
    description: 'Compact and cozy apartment in the historic city center, perfect for single occupants. Convenient access to public transport.',
    status: 'For Sale',
    type: 'Apartment',
    category: 'Apartment',
    year: '2015',
    agent: 'Michael Brown',
    agent_image: '/assets/micheal_brown.jpg',
    agent_phone: '+1 (555) 123-4567',
    agent_email: 'michael.brown@example.com',
    agent_website: 'https://www.michael-brown.com',
    agent_facebook: 'https://www.facebook.com/michael.brown',
    agent_twitter: 'https://www.twitter.com/michael.brown',
    agent_instagram: 'https://www.instagram.com/michael.brown',
  },
  {
    id: 30,
    image: '/assets/los_Angeles.jpg',
    label: 'LA Downtown Loft',
    price: '$1,100,000',
    address: '789 Broadway, Los Angeles, CA 90012',
    area: '1000 sq.ft',
    bedroom: '2',
    bathroom: '2',
    description: 'Industrial-chic loft in a vibrant downtown area. Features exposed brick and modern finishes.',
    status: 'For Rent',
    type: 'Apartment',
    category: 'Apartment',
    year: '2016',
    agent: 'Michael Brown',
    agent_image: '/assets/micheal_brown.jpg',
    agent_phone: '+1 (555) 123-4567',
    agent_email: 'michael.brown@example.com',
    agent_website: 'https://www.michael-brown.com',
    agent_facebook: 'https://www.facebook.com/michael.brown',
    agent_twitter: 'https://www.twitter.com/michael.brown',
    agent_instagram: 'https://www.instagram.com/michael.brown',
  },
  {
    id: 31,
    image: '/assets/british-stylish.jpg',
    label: 'Stylish British Apartment',
    price: '$900,000',
    address: '10 Downing St, London, UK SW1A 2AA',
    area: '950 sq.ft',
    bedroom: '2',
    bathroom: '1',
    description: 'A beautifully designed apartment with a classic British flair. Located in a prestigious area.',
    status: 'For Sale',
    type: 'Apartment',
    category: 'Apartment',
    year: '2014',
    agent: 'Michael Brown',
    agent_image: '/assets/micheal_brown.jpg',
    agent_phone: '+1 (555) 123-4567',
    agent_email: 'michael.brown@example.com',
    agent_website: 'https://www.michael-brown.com',
    agent_facebook: 'https://www.facebook.com/michael.brown',
    agent_twitter: 'https://www.twitter.com/michael.brown',
    agent_instagram: 'https://www.instagram.com/michael.brown',
  },
  {
    id: 32,
    image: '/assets/butter-storey.jpg',
    label: 'Multi-Story Office Building',
    price: '$10,000,000',
    address: '500 Commerce Ave, New York, NY 10001',
    area: '10000 sq.ft',
    description: 'A complete multi-story office building, suitable for a large corporation. Modern infrastructure and amenities.',
    status: 'For Sale',
    type: 'Office',
    category: 'Office',
    year: '2022',
    agent: 'Frank Thomas',
    agent_image: '/assets/frank-thomas.jpg',
    agent_phone: '+1 (111) 222-3333',
    agent_email: 'frank.thomas@example.com',
    agent_website: 'https://www.frank-thomas.com',
    agent_facebook: 'https://www.facebook.com/frank.thomas',
    agent_twitter: 'https://www.twitter.com/frank.thomas',
    agent_instagram: 'https://www.instagram.com/frank.thomas',
    agent_linkedin: 'https://www.linkedin.com/in/frank.thomas',
  },
  {
    id: 33,
    image: '/assets/carl-brymo.jpg',
    label: 'Carl Brymo Business Center',
    price: '$6,000,000',
    address: '700 Innovation Rd, San Jose, CA 95110',
    area: '4000 sq.ft',
    description: 'A contemporary business center with various office units, ideal for startups and small to medium-sized businesses.',
    status: 'For Rent',
    type: 'Office',
    category: 'Office',
    year: '2020',
    agent: 'Frank Thomas',
    agent_image: '/assets/frank-thomas.jpg',
    agent_phone: '+1 (111) 222-3333',
    agent_email: 'frank.thomas@example.com',
    agent_website: 'https://www.frank-thomas.com',
    agent_facebook: 'https://www.facebook.com/frank.thomas',
    agent_twitter: 'https://www.twitter.com/frank.thomas',
    agent_instagram: 'https://www.instagram.com/frank.thomas',
    agent_linkedin: 'https://www.linkedin.com/in/frank.thomas',
  }
];

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const id = searchParams.get('id');

  if (id) {
    const property = properties.find((p) => String(p.id) === id);
    if (property) {
      return NextResponse.json(property);
    } else {
      return NextResponse.json({ error: 'Property not found' }, { status: 404 });
    }
  }

  // Return all properties if no id is specified
  return NextResponse.json(properties);
}
