import Navbar from "./components/nav";
import "./globals.css";
import Footer from "./components/footer";

export const metadata = {
  title: "ESTATE - HOUSING",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
