
import Navbar from "./components/nav";
import "./globals.css";
import Footer from "./components/footer";
import Preloader from "./components/preloader";
import PageTransition from "./components/pageTransition"; 

export const metadata = {
  title: "ESTATE - HOUSING",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <Preloader/>
        <PageTransition> {/* Wrap children with PageTransition */}
          <Navbar/>
            {children}
          <Footer/>
        </PageTransition>
      </body>
    </html>
  );
}
